# Generated by Django 5.0.2 on 2024-09-02 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='status',
            field=models.CharField(blank=True, choices=[('applied', 'Applied'), ('accepted', 'Accepted')], default='applied', max_length=20, null=True),
        ),
    ]
