# Generated by Django 5.0.2 on 2024-09-04 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_application_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='teacher',
            new_name='student',
        ),
    ]
