# Generated by Django 5.0.2 on 2024-09-04 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_rename_teacher_application_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='cancel',
            field=models.BooleanField(default=False),
        ),
    ]
