# Generated by Django 5.0.2 on 2024-09-02 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('normalUser', '0003_alter_teacher_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='days_per_week',
            field=models.IntegerField(blank=True, default=5, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='medium_of_instruction',
            field=models.CharField(blank=True, choices=[('Bangla', 'Bangla_Medium'), ('English', 'English_Version')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='minimum_salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='status',
            field=models.CharField(blank=True, choices=[('Available', 'Available'), ('Not_Available', 'Not Available')], default='Available', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='tuition_district',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='tutoring_experience',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='mobile',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
