# Generated by Django 5.0.2 on 2024-09-04 07:21

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_rename_teacher_application_student'),
        ('normalUser', '0004_teacher_days_per_week_teacher_gender_and_more'),
        ('tuition', '0005_subjectchoice_remove_tuition_subjects_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Teacher',
            new_name='Student',
        ),
    ]
