# Generated by Django 5.0.2 on 2024-09-04 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('normalUser', '0006_remove_student_days_per_week_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Group',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='school',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
