# Generated by Django 5.0.2 on 2024-09-02 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('normalUser', '0003_alter_teacher_image'),
        ('tuition', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rating', models.CharField(choices=[('⭐', '⭐'), ('⭐⭐', '⭐⭐'), ('⭐⭐⭐', '⭐⭐⭐'), ('⭐⭐⭐⭐', '⭐⭐⭐⭐'), ('⭐⭐⭐⭐⭐', '⭐⭐⭐⭐⭐')], max_length=100)),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='normalUser.teacher')),
                ('tuition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tuition.tuition')),
            ],
        ),
    ]
