# Generated by Django 5.0.2 on 2024-09-02 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuition', '0002_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tuition',
            name='available_time',
            field=models.CharField(max_length=100),
        ),
    ]
