# Generated by Django 5.0.2 on 2024-09-02 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_pannel', '0001_initial'),
        ('tuition', '0003_alter_tuition_available_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tuition',
            name='available_time',
        ),
        migrations.RemoveField(
            model_name='tuition',
            name='class_level',
        ),
        migrations.AddField(
            model_name='tuition',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_pannel.adminmodel'),
        ),
        migrations.AddField(
            model_name='tuition',
            name='availability',
            field=models.BooleanField(default=True, help_text='Availability status of the tuition'),
        ),
        migrations.AddField(
            model_name='tuition',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tuition',
            name='medium',
            field=models.CharField(blank=True, choices=[('Bangla', 'Bangla_Medium'), ('English', 'English_Version')], help_text='Medium of instruction', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tuition',
            name='number_of_students',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='tuition',
            name='preferred_tutor_gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], help_text='Preferred gender of tutor', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tuition',
            name='salary',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Salary offered per month', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='tuition',
            name='student_gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tuition',
            name='subjects',
            field=models.CharField(blank=True, choices=[('General_Math', 'General Math'), ('Bangla', 'Bangla'), ('English', 'English'), ('General_Science', 'General Science'), ('Religion', 'Religion'), ('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Biology', 'Biology'), ('Higher_Math', 'Higher Math'), ('All_Subjects', 'All Subjects')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tuition',
            name='tuition_class',
            field=models.CharField(blank=True, choices=[('Class 1', 'Class 1'), ('Class 2', 'Class 2'), ('Class 3', 'Class 3'), ('Class 4', 'Class 4'), ('Class 5', 'Class 5'), ('Class 6', 'Class 6'), ('Class 7', 'Class 7'), ('Class 8', 'Class 8'), ('Class 9', 'Class 9'), ('Class 10', 'Class 10'), ('HSC 1', 'HSC-1st_Year'), ('HSC 2', 'HSC-2nd_Year')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tuition',
            name='tutoring_time',
            field=models.CharField(blank=True, choices=[('Morning', 'Morning'), ('Afternoon', 'Afternoon'), ('Evening', 'Evening')], help_text='Time for tutoring', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='tuition',
            name='description',
            field=models.TextField(blank=True, help_text='Detailed Description of the tuition', null=True),
        ),
    ]
