# Generated by Django 5.0.2 on 2024-09-02 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuition', '0004_remove_tuition_available_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('General_Math', 'General Math'), ('Bangla', 'Bangla'), ('English', 'English'), ('General_Science', 'General Science'), ('Religion', 'Religion'), ('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Biology', 'Biology'), ('Higher_Math', 'Higher Math'), ('All_Subjects', 'All Subjects')], max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='tuition',
            name='subjects',
        ),
        migrations.AddField(
            model_name='tuition',
            name='subjects',
            field=models.ManyToManyField(blank=True, null=True, related_name='tuitions', to='tuition.subjectchoice'),
        ),
    ]
