# Generated by Django 5.0.2 on 2024-09-04 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuition', '0006_alter_tuition_preferred_tutor_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tuition',
            name='medium',
            field=models.CharField(blank=True, choices=[('Both', 'Both'), ('Bangla', 'Bangla_Medium'), ('English', 'English_Version')], help_text='Medium of instruction', max_length=50, null=True),
        ),
    ]
