# Generated by Django 5.0.2 on 2024-09-04 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuition', '0007_alter_tuition_medium'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tuition',
            name='preferred_tutor_gender',
        ),
        migrations.AddField(
            model_name='tuition',
            name='tutor_gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], help_text='Preferred gender of tutor', max_length=50, null=True),
        ),
    ]
