# Generated by Django 5.0.2 on 2024-09-04 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuition', '0008_remove_tuition_preferred_tutor_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tuition',
            name='tutoring_experience',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
