# Generated by Django 5.0.2 on 2024-09-04 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_pannel', '0001_initial'),
        ('tuition', '0009_tuition_tutoring_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='reviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_pannel.adminmodel'),
        ),
    ]
