# Generated by Django 5.0.2 on 2024-09-04 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('normalUser', '0007_student_group_student_school'),
        ('tuition', '0010_alter_review_reviewer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='reviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='normalUser.student'),
        ),
    ]
